---
title: "Pitch Presentation"
author: "Vibhutesh"
date: "6th MArch 2019"
output: ioslides_presentation
---

## The Question

OK, you've made your shiny app, now it's time to make your pitch. You get 5 slides (inclusive of the title slide) to pitch a your app. You're going to create a web page using Slidify or Rstudio Presenter with an html5 slide deck.

Here's what you need

5 slides to pitch our idea done in Slidify or Rstudio Presenter
Your presentation pushed to github or Rpubs
A link to your github or Rpubs presentation pasted into the provided text box


## The Goal 

Your presentation must satisfy the following

It must be done in Slidify or Rstudio Presenter
It must be 5 pages
It must be hosted on github or Rpubs
It must contained some embedded R code that gets run when slidifying the document

## The Principle

Forest Area Cover
```{r echo=FALSE}
urlfile<-'https://raw.github.com/vibhutesh/dataproducts/master/forestarea.csv'

area <- read.csv(url(urlfile))

     # Render a barplot 
     barplot(area[,1],  
             main=area$Lakdweep, 
             ylab="Forest Area Cover (Sq-Meter)", 
             xlab="Year") 
```

## The Source

UNOTE: Slidify is no longer compatible with with Rpubs. If you choose to use Slidify you must share your presentation using GitHub Pages.

Notice to publish your slidify presentation to github or Rpubs, there's the publish command. This link outlines how to do it (it's one line).

http://slidify.org/publish.html

Rstudio presenter has a button to publish directly to Rpubs https://support.rstudio.com/hc/en-us/articles/200714023-Displaying-and-Distributing-Presentations. If you are using Rpubs, put in the link to the presentation into the submission box as a http:// link not a https:// link.

You can also publish using both formats to github manually using gh-pages, though your github branch must have a .nojekyll fle and be on a branch names gh-pages. There's more on gh-pages here https://pages.github.com/ and there is a video lecture outlining how to do this.